# Change these first
owner: HEALFORM # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: HEALFORM
    url: https://www.healform.de
  - name: myHEALFORM
    url: https://my.healform.de
  - name: HEALFORM Chat
    url: https://chat.healform.de
  - name: HEALFORM Display-Widget
    url: https://display-widget.healform.de
  - name: HEALFORM Franchise
    url: https://franchise.healform.de
  - name: HEALFORM Liquid
    url: https://liquid.healform.de
  - name: HEALFORM Server
    url: https://api.healform.de
  - name: HEALFORM Support-Center
    url: https://support.healform.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/HEALFORM/status/master/static/img/liquid.png
  name: HEALFORM Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/HEALFORM/status). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  themeUrl: https://raw.githubusercontent.com/HEALFORM/status/master/assets/theme.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
